Algoritmo "Procedimento"

// Disciplina   : Lógica de Programação e Algoritmos

//------------------------------------------------------------------------+
// Descrição   : Algotiymo recebe TEXTO em letras MAIUSCULAS e retorna
//
//               um TEXTO em letras MINUSCULAS.
//
//               Utiliza Procedimento para pular linhas.
//------------------------------------------------------------------------+



Var

// Seção de Declarações das variáveis

// mi = minusculo , ma = maiusculo

txt_mi , txt_ma : caractere



//------------------------------------------------------------------------+
// Procedimento
//------------------------------------------------------------------------+

Procedimento Pula_Linhas

Var

Inicio

//------------------------------------------------------------------------+
// Pulando linhas
//------------------------------------------------------------------------+

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

FimProcedimento



Inicio

// Seção de Comandos, procedimento, funções, operadores, etc...

//------------------------------------------------------------------------+
// Apresentação
//------------------------------------------------------------------------+

escreval ("")

escreval ("  PROCEDIMENTO")

escreval ("")

escreval ("  +---------------------------------------------------------------------------+")
escreval ("  |  Software recebe TEXTO em letras MAIUSCULAS e retorna um TEXTO            |")
escreval ("  |                                                                           |")
escreval ("  |  em letras MINUSCULAS.                                                    |")
escreval ("  +---------------------------------------------------------------------------+")

escreval ("")

escreva ("   Texto MAIUSCULO : ")

leia (txt_ma)

txt_mi <- Minusc (txt_ma)

escreval ("")

escreval ("   Texto minusculo : " , txt_mi)



//------------------------------------------------------------------------+
// Pulando linhas
//------------------------------------------------------------------------+

Pula_Linhas

FimAlgoritmo
